### PR TITLE
Proposed simple expressions

### PR DESCRIPTION
**Pull request by jonasfj**
I think we can make an outright crazy amount of test cases... We probably should make some really complex one that tests multiple features in one case :)

### CODE REVIEW

**Comment by hammad13060** [comment]
This looks nice. However I am also thinking about cases where ```${....}``` will evaluate expressions (just like those you mentioned) and then it will perform interpolation.

**Comment by jonasfj** [comment]
Absolutely, feel free to add more examples. This doesn't even cover expressions like `2 + 3 * 4` which we properly need to test with too :)

**Comment by jonasfj** [comment]
@hammad13060, I've enabled branch protection, so you need to click the review button before we can land this...

IMO, please feel free to add similar examples.. Let's build up a huge spec/list-of-test-cases before we get too far with implementing it.... Then we can implement one feature at the time and see the number of failing testcases decline :)

**Comment by hammad13060** [comment]
Yup, I will add more test cases to the specs.

**Pull request merged**
