### PR TITLE
$json sorting unicode strings (issue #222)

### PR DESCRIPTION
**Pull request by Biboswan**

### CODE REVIEW

**Comment by Biboswan** [comment]
@djmitche  add the test cases

**Comment by djmitche** [comment]
```
     Unknown assertation failure occured, assumed `'{"A\\u0012ၰ00":"hi","A𤀀":"hello","e󣿾猫":"hey"}'`
to deeply equal `'{"\\u0041\\u0012\\u107000":"hi", "A\\U00024000":"hello", "e\\U000E3FFE\\u732b":"hey"}'`
```

**Comment by djmitche** [comment]
I think you need to use single-quotes here, so that the `\U` are interpreted:
https://github.com/Biboswan/json-e/blob/d5ab740940818fadb759d99e3e18321d09205a07/specification.yml#L597
```
result: '{"\u0055\u0045": 3, "\u3347\u0050": 1 , "\uE1FF\u0010": 2}'
```
should be
```
result: "{\"\u0055\u0045\": 3, \"\u3347\u0050\": 1 , \"\uE1FF\u0010\": 2}"
```

**Comment by Biboswan** [comment]
if 
````
 result:{\"\u0055\u0045": 3, \"\u3347\u0050": 1 , \"\uE1FF": 2}
````
then result becomes
````
`{ '\\"\\u0055\\u0045"': 3, '\\"\\u3347\\u0050"': 1, '\\"\\uE1FF"': 2 }`
````

If just quotes around the object is removed i.e
````
{"\u0055\u0045": 3, "\u3347\u0050": 1 , "\uE1FF": 2}
````
then
````
result :{ UE: 3, '㍇P': 1, '': 2 }
````

But necessary double quotes are also missing around the keys. Using more quotes around keys prevents unicode to be interpreted.
Seems like only some parser can handle this.

**Comment by djmitche** [comment]
I'll see if I can get it to work.  If not, maybe we can add some special-casing to the tests.

**Comment by djmitche** [comment]
This can get a little tricky since we need to write the expected values as an escaped string for the YAML parser.  That means we need to use double-quotes (`result: ".."`) and then escape `"` and `\` in the string itself when we want them to appear literally.  We can use `\uXXXX` and `\Uxxxxxxxx` for unicode characters.  Also, whitespace matters in the JSON output. With all of that fixed, the following works in JS:

```yaml
---
title:    sorting pairs by unicode key strings sorts lexically by codepoint
context:  {}
template: {$json: {"\u3347\u0050": 1, "\uE1FF\u0100": 2, "\u0055\u0045": 3}}
result:   "{\"\u0055\u0045\":3,\"\u3347\u0050\":1,\"\uE1FF\u0100\":2}"
---
title:    sorting pairs by unicode key strings sorts lexically by codepoint, even with chars above base plane
context:  {}
template: {$json: {"\U0001F809\u732b":'hey', "Z\U00010000P": 1, "\U000E1FFF\u0103": 2, "UaE": 3}}
result:   "{\"UaE\":3,\"Z\U00010000P\":1,\"\U000E1FFF\u0103\":2,\"\U0001F809\u732b\":\"hey\"}"
```

But it fails in Python:

```
======================================================================
FAIL: test.test_specification.test('$json: sorting pairs by unicode key strings sorts lexically by codepoint',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dustin/go/src/github.com/taskcluster/json-e/.eggs/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/dustin/go/src/github.com/taskcluster/json-e/test/test_specification.py", line 29, in test
    '{!r} != {!r}'.format(res, spec['result'])
AssertionError: u'{"UE":3,"\\u3347P":1,"\\ue1ff\\u0100":2}' != u'{"UE":3,"\u3347P":1,"\ue1ff\u0100":2}'

======================================================================
FAIL: test.test_specification.test('$json: sorting pairs by unicode key strings sorts lexically by codepoint, even with chars above base plane',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dustin/go/src/github.com/taskcluster/json-e/.eggs/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/dustin/go/src/github.com/taskcluster/json-e/test/test_specification.py", line 29, in test
    '{!r} != {!r}'.format(res, spec['result'])
AssertionError: u'{"UaE":3,"Z\\ud800\\udc00P":1,"\\udb47\\udfff\\u0103":2,"\\udb4f\\udffe\\u732b":"hey"}' != u'{"UaE":3,"Z\U00010000P":1,"\U000e1fff\u0103":2,"\U0001f809\u732b":"hey"}'
```

So let's back up a little bit and write some tests for representations of unicode characters in $json output, before we start worrying about sort order.

```yaml
title:    representation of various unicode codepoints are consistent
context:  {}
template: {$json: ["\x10", "Z", "\u0103","\U0001F809"]}
result:   "[\"\\u0010\",\"Z\",\"\u0103\",\"\U0001F809\"]"
```

This passes in golang and in JS, but not in Python.  It expects a `\u`-escaped string, an ASCII "Z", a literal LATIN SMALL LETTER A WITH BREVE (codepoint 0103), and a literal UPWARDS ARROW WITH LARGE TRIANGLE ARROWHEAD (codepoint 0001f809).

Python gives:

```
AssertionError: u'["\\u0010","Z","\\u0103","\\ud83e\\udc09"]' != u'["\\u0010","Z","\u0103","\U0001f809"]'
```

here Python has the same result for the first two characters, but uses a `\u`-escaped 0103 and, worse, represents codepoint 0001f809 as the `\u`-escaped surrogate pair d83e-dc09.  It looks like Python is only using ASCII characters in the output, with `\u` escapes for anything non-ASCII.  @indygreg helpfully pointed me at the `ensure_ascii` to `json.dump`, which defaults to True.  Setting that to False seems to fix everything!

**Comment by djmitche** [comment]
I pushed my changes to this PR.  Let me know what you think?

**Comment by djmitche** [comment]
It looks like the golang failures are typical metalinter failures and not related to this patch:

```
jsone.go:1::warning: file is not gofmted with -s (gofmt)
jsone.go:1::warning: file is not goimported (goimports)
```

**Comment by djmitche** [comment]
Whoops, I meant to squash that!

**Pull request merged**
