### PR TITLE
Initial outline for specification

### PR DESCRIPTION
**Pull request by jonasfj**
@hammad13060, @djmitche, @imbstack,
An initial outline for the `json-e` spec... We need a LOT more features, so write a section and file a PR :)
The file might get so long that we need a file per section... but for now this works.

I think we should do specification changes in a PR before implementing a feature, this way we can discuss features by example before we implement them. And we have test cases when we start implementing them.

@hammad13060, please accept invitation to join the organization (it requires you enable 2FA if not already).

### CODE REVIEW

**Comment by hammad13060** [comment]
@all 

I have updated [json-e](https://github.com/hammad13060/json-e) for following features

1. ${...} for string interpolation
2. $eval for object replacement
3. $if construct : $then and $else support evaluation of 1 and 2 mentioned above. If we have something like $then: <<<some js object>>> it will be recursively evaluated.
2 $switch construct: It supports 1 and 2 mentioned above along with recursive object evaluation like in if-else construct.

**Comment by jonasfj** [comment]
@hammad13060, I propose that we proceed by:
 A) gathering consensus on syntax by changing `specification.yml` in this repo through PRs
 B) submitting PRs to this repo with implementation of features from the specification

That way the code goes through a review process.

**Comment by jonasfj** [comment]
@hammad13060 anything controversial in this PR? if not I suggest we land it... So we make PRs ontop of it rather than copying eveyrthing into new proposals.

Ie. suggesting changes/additions to the spec is perfectly fine.

**Comment by hammad13060** [comment]
I have gone through it and it seems good. Yes lets land it (that will be more efficient).

**Pull request merged**
