### PR TITLE
spec 2 proposal with different $fromNow format

### PR DESCRIPTION
**Pull request by hammad13060**
@jonasfj @djmitche and @imbstack 

I propose following specs for ```$fromNow```

```javascript
{
  $fromNow: {
      d/day/days: <some days>,
      h/hour/hours: <some hours>,
      m/min/minutes: <some minutes>
   }
}
```

So we will have something like this

```javascript
{
  $fromNow: {d: 2, h: 12, m: 32},
  $fromNow: {day: 2, hour: 12, min: 32},
  $fromNow: {days: 2, hours: 12, minutes: 32},
}
```

### CODE REVIEW

**Comment by jonasfj** [comment]
I like this a lot... That we can also have $eval inside the parameters for
$fromNow.

The only argument for the string syntax is that it's shorter... We have the
parser for it implemented in taskcluster-client.

Hmm, perhaps we can have both... Parse string if given other use object...

Den 19. jan. 2017 1.42 PM skrev "Hammad Akhtar" <notifications@github.com>:

**Comment by hammad13060** [comment]
ya keeping both seems good :)

**Comment by jonasfj** [comment]
r+

But let's keep the string syntax too. It's easy to parse with a regexp.

**Comment by hammad13060** [comment]
I was also thinking that instead of having ```d/day/days```, ```h/hour/hours``` and ```m/min/minutes``` lets limit ourselves to ```d, h, m``` only

**Comment by jonasfj** [comment]
In the string format I really like having the ability to write `days` and `day` it so nice to read...

**Comment by hammad13060** [comment]
for the string part lets keep all the variants, however for time specification using object, lets limit ourselves to to d, m, h.

**Comment by jonasfj** [comment]
okay, I can support that...

**Comment by jonasfj** [comment]
actually @imbstack had a good point that 99% of the time the `$fromNow` construct is used with a string like: `'1 day'` or `'20 minutes'`, so maybe this object support is overkill.

If people want to pass in variables, they can use string interpolation, but I'm guessing that 99% of time it'll be faster and shorter to just write `{$fromNow: '2 hours'}`

**Comment by hammad13060** [comment]
Okay. Then probably we should go with the string format only.

**Comment by jonasfj** [comment]
Yeah, let's stick with string for now...

**Pull request closed without merging**
